language: cpp

sudo: required
dist: trusty

compiler:
  - clang
  - gcc

install:
  - bash scripts/setup.sh

script:
  - cd build && cmake .. && make && ./tests

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - bernardo@bernardosulzbach.com
