language: cpp

sudo: required
dist: trusty

compiler:
  - clang
  - gcc

install:
  - sudo apt-get update
  - sudo apt-get upgrade clang gcc
  - sudo apt-get install -y libegl1-mesa-dev libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev

script:
  - mkdir build && cd build && cmake .. && make && ./tests

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - bernardo@bernardosulzbach.com
