language: cpp

sudo: required
dist: trusty

matrix:
  include:
    - env: COMPILER=clang-5.0
      addons:
        - apt:
            packages:
              - clang-5.0
              - libegl1-mesa-dev
              - libsdl2-dev
              - libsdl2-ttf-dev
              - libsdl2-image-dev
            sources:
              - ubuntu-toolchain-r-test
              - llvm-toolchain-trusty-5.0
    - env: COMPILER=g++-7
      addons:
        - apt:
            packages:
              - g++-7
              - libegl1-mesa-dev
              - libsdl2-dev
              - libsdl2-ttf-dev
              - libsdl2-image-dev
            sources:
              - ubuntu-toolchain-r-test
              - llvm-toolchain-trusty-5.0

script:
  - mkdir build && cd build && cmake .. CMAKE_CXX_COMPILER=$COMPILER && make && ./tests

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - bernardo@bernardosulzbach.com
