language: c
sudo: required
dist: trusty

compiler:
  - clang
  - gcc

install:
  - bash scripts/setup.sh

script:
  - bash scripts/test.sh

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - mafagafogigante@gmail.com
