language: cpp

sudo: required
dist: trusty

compiler:
  - clang-5.0
  - g++-7

addons:
  apt:
    packages:
      - g++-7
      - clang-5.0
      - libegl1-mesa-dev
      - libsdl2-dev
      - libsdl2-ttf-dev
      - libsdl2-image-dev
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0

script:
  - mkdir build && cd build && cmake .. && make && ./tests

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - bernardo@bernardosulzbach.com
